experiment:
  name: "MOSEI (CMAMs A-VT): Training"
  debug: False
  device: "cuda"
  do_test: True

data:
  train:
    dataset: "mosei"
    data_fp: "DATA/MOSEI/aligned_50.pkl"
    target_modality: !Modality "multimodal"
    selected_missing_types:
      - "azz"
    split: "train"
    shuffle: True
    drop_last: True
    pin_memory: True
  validation:
    dataset: "mosei"
    data_fp: "DATA/MOSEI/aligned_50.pkl"
    target_modality: !Modality "multimodal"
    selected_missing_types:
      - "azz"
    split: "valid"
    drop_last: True
    pin_memory: True
    shuffle: True
  test:
    dataset: "mosei"
    data_fp: "DATA/MOSEI/aligned_50.pkl"
    target_modality: !Modality "multimodal"
    selected_missing_types:
      - "azz"
    split: "test"
    drop_last: True
    pin_memory: True
    shuffle: True



model:
  name: "UttFusionModel"
  pretrained_path: "experiments/mosei/models/MOSEI_(Classification):_Baseline_Training/{run_id}/mosei_model__loss_best.pth"
  input_size_a: 74
  embd_size_a: 96
  embd_method_a: "maxpool"
  input_size_v: 35
  embd_size_v: 96
  embd_method_v: "maxpool"
  input_size_t: 768
  embd_size_t: 96
  classification_layers: [96, 96]
  output_dim: 3
  dropout: 0.5
  use_bn: False

cmam:
  name: "DualCMAM"
  input_modality: !Modality "audio"
  input_encoder_info:
    audio:
      name: "LSTMEncoder"
      input_size: 74
      hidden_size: 96
      embd_method: "maxpool"
  target_modality_one: !Modality "video"
  target_modality_two: !Modality "text"
  target_modality_one_embd_size: 96
  target_modality_two_embd_size: 96
  decoder_hidden_size: 256
  shared_encoder_output_size: 96
  dropout: 0.4
  target_missing_type: "azz"
  binarize: True

training:
  epochs: 25
  num_modalities: 3
  batch_size: 256
  optimizer: "adam"
  optim_kwargs:
    input_encoder_kwargs: &shared_optimizer_kwargs
      lr: 0.01
      weight_decay: 0.0001
      betas: [0.9, 0.999]
    target_modality_one_kwargs:
      lr: 0.001
      weight_decay: 0.0001
      betas: [0.9, 0.999]
    target_modality_two_kwargs:
      lr: 0.01
      weight_decay: 0.0001
      betas: [0.9, 0.999]
  criterion: "cmam"
  criterion_kwargs:
    cosine_weight: 1.0
    mse_weight: 1.0
    mae_weight: 1.0
    cls_weight: 0.05
    rec_weight: 1.0
    mmd_weight: 0.1
    moment_weight: 0.1
  target_missing_type: "azz"
  scheduler: "plateau"
  do_tsne: False
  
logging:
  save_metric: "loss"
  log_path: "experiments/mosei/logs/{experiment_name}/{run_id}/"
  model_output_path: "experiments/mosei/models/{experiment_name}/cmam_A_to_VL_{save_metric}_{run_id}.pth" 
  metrics_path: "experiments/mosei/metrics/{experiment_name}/{run_id}/cmam_A_to_VT"

metrics:
  prediction_metrics:
    Accuracy:
      function: "sklearn.metrics.accuracy_score"
    F1_Micro:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "micro"
    F1_Macro:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "macro"
    F1_Weighted:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "weighted"
    UAR:
      function: "sklearn.metrics.recall_score"
      kwargs:
        average: "macro"
        zero_division: 0
    Precision_Macro:
      function: "sklearn.metrics.precision_score"
      kwargs:
        average: "macro"
        zero_division: 0
    Recall_Macro:
      function: "sklearn.metrics.recall_score"
      kwargs:
        average: "macro"
        zero_division: 0
    Precision_Weighted:
      function: "sklearn.metrics.precision_score"
      kwargs:
        average: "weighted"
        zero_division: 0
    Recall_Weighted:
      function: "sklearn.metrics.recall_score"
      kwargs:
        average: "weighted"
        zero_division: 0
    Precision_Micro:
      function: "sklearn.metrics.precision_score"
      kwargs:
        average: "micro"
        zero_division: 0
    Recall_Micro:
      function: "sklearn.metrics.recall_score"
      kwargs:
        average: "micro"
        zero_division: 0
    ConfusionMatrix:
      function: sklearn.metrics.confusion_matrix
      kwargs:
        labels: [0, 1]

