experiment:
  name: "MOSEI (Classification): Baseline Training"
  debug: True
  run_id: 2

data:
  train:
    dataset: "mosi"
    data_fp: "DATA/MOSEI/aligned_50.pkl"
    target_modality: "multimodal"
    split: "train"
    shuffle: True
    drop_last: True
    pin_memory: True


  validation:
    dataset: "mosi"
    data_fp: "DATA/MOSEI/aligned_50.pkl"
    target_modality: "multimodal"
    split: "valid"
    drop_last: True
    pin_memory: True


  test:
    dataset: "mosi"
    data_fp: "DATA/MOSEI/aligned_50.pkl"
    target_modality: "multimodal"
    split: "test"
    drop_last: True
    pin_memory: True


model:
  name: "UttFusionModel"
  kwargs:
    input_size_a: 74
    embd_size_a: 96
    embd_method_a: "maxpool"
    input_size_v: 35
    embd_size_v: 96
    embd_method_v: "maxpool"
    input_size_l: 768
    embd_size_l: 96
    classification_layers: [96, 96]
    output_dim: 3
    dropout: 0.5
    use_bn: False

training:
  mode: "baseline"
  epochs: 20
  batch_size: 256
  early_stopping_patience: 5
  early_stopping_metric: "loss"
  optimizer: "adam"
  optim_kwargs:
    weight_decay: 0.00001
    lr: 0.0002
  criterion: "cross_entropy"
  scheduler: "lambda"
  scheduler_args:
    lr_lambda: "lambda epoch: 1.0 - max(0, epoch + epoch_count - niter) / float(niter_decay + 1)"
    epoch_count: 1
    niter: 10
    niter_decay: 10

logging:
  save_metric: "UAR_AVL"
  log_path: "experiments/mosei/logs/{experiment_name}/{run_id}/"
  model_output_path: "experiments/mosei/models/{experiment_name}/{run_id}/mosei_model_{save_metric}.pth" 
  metrics_paths: "experiments/mosei/metrics/{experiment_name}/"

metrics:
  metrics:
    Accuracy:
      function: "sklearn.metrics.accuracy_score"
    F1_Micro:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "micro"
    F1_Macro:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "macro"
    F1_Weighted:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "weighted"
    UAR:
      function: "sklearn.metrics.recall_score"
      kwargs:
        average: "macro"
        zero_division: 0
    Precision_Macro:
      function: "sklearn.metrics.precision_score"
      kwargs:
        average: "macro"
        zero_division: 0
    Recall_Macro:
      function: "sklearn.metrics.recall_score"
      kwargs:
        average: "macro"
        zero_division: 0
    Precision_Weighted:
      function: "sklearn.metrics.precision_score"
      kwargs:
        average: "weighted"
        zero_division: 0
    Recall_Weighted:
      function: "sklearn.metrics.recall_score"
      kwargs:
        average: "weighted"
        zero_division: 0
    Precision_Micro:
      function: "sklearn.metrics.precision_score"
      kwargs:
        average: "micro"
        zero_division: 0
    Recall_Micro:
      function: "sklearn.metrics.recall_score"
      kwargs:
        average: "micro"
        zero_division: 0
    NonZeroAcc:
      function: metrics.mosi.binary_accuracy_non_zero
    NonZeroF1:
      function: metrics.mosi.binary_f1_score_non_zero
    HasZeroAcc:
      function: metrics.mosi.binary_accuracy
    HasZeroF1:
      function: metrics.mosi.binary_f1_score
    ConfusionMatrix:
      function: sklearn.metrics.confusion_matrix