experiment:
  name: "MOSEI (Classification): Baseline Training"
  debug: False

data:
  train:
    dataset: "mosei"
    data_fp: "DATA/MOSEI/aligned_50.pkl"
    target_modality: !Modality "multimodal"
    split: "train"
    shuffle: True
    drop_last: True
    pin_memory: True


  validation:
    dataset: "mosei"
    data_fp: "DATA/MOSEI/aligned_50.pkl"
    target_modality: !Modality "multimodal"
    split: "valid"
    drop_last: True
    pin_memory: True
    shuffle: True

  test:
    dataset: "mosei"
    data_fp: "DATA/MOSEI/aligned_50.pkl"
    target_modality: !Modality "multimodal"
    split: "test"
    drop_last: True
    pin_memory: True
    shuffle: True

model:
  name: "UttFusionModel"
  input_size_a: 74
  embd_size_a: 96
  embd_method_a: "maxpool"
  input_size_v: 35
  embd_size_v: 96
  embd_method_v: "maxpool"
  input_size_t: 768
  embd_size_t: 96
  classification_layers: [96, 96]
  output_dim: 3
  dropout: 0.5
  use_bn: False

training:
  mode: "baseline"
  epochs: 20
  batch_size: 256
  early_stopping: True
  early_stopping_patience: 7
  early_stopping_metric: "loss"
  optimizer: "adam"
  optim_kwargs:
    weight_decay: 0.00001
    lr: 0.0002
  criterion: "cross_entropy"
  scheduler: "lambda"
  scheduler_args:
    lr_lambda: "lambda epoch: 1.0 - max(0, epoch + epoch_count - niter) / float(niter_decay + 1)"
    epoch_count: 1
    niter: 10
    niter_decay: 10

logging:
  save_metric: "loss"
  log_path: "experiments/mosei/logs/{experiment_name}/{run_id}/"
  model_output_path: "experiments/mosei/models/{experiment_name}/{run_id}/mosei_model_{save_metric}.pth" 
  metrics_path: "experiments/mosei/metrics/{experiment_name}/{run_id}/"

metrics:
  metrics:
    Accuracy:
      function: "sklearn.metrics.accuracy_score"
    F1_Micro:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "micro"
    F1_Macro:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "macro"
    F1_Weighted:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "weighted"
    UAR:
      function: "sklearn.metrics.recall_score"
      kwargs:
        average: "macro"
        zero_division: 0
    Precision_Macro:
      function: "sklearn.metrics.precision_score"
      kwargs:
        average: "macro"
        zero_division: 0
    Recall_Macro:
      function: "sklearn.metrics.recall_score"
      kwargs:
        average: "macro"
        zero_division: 0
    Precision_Weighted:
      function: "sklearn.metrics.precision_score"
      kwargs:
        average: "weighted"
        zero_division: 0
    Recall_Weighted:
      function: "sklearn.metrics.recall_score"
      kwargs:
        average: "weighted"
        zero_division: 0
    Precision_Micro:
      function: "sklearn.metrics.precision_score"
      kwargs:
        average: "micro"
        zero_division: 0
    Recall_Micro:
      function: "sklearn.metrics.recall_score"
      kwargs:
        average: "micro"
        zero_division: 0
    ConfusionMatrix:
      function: sklearn.metrics.confusion_matrix
      kwargs:
        labels: [0, 1]