experiment:
  name: "AVMNIST (CMAMs I-A): Baseline Training"
  debug: False

data:
  train:
    dataset: "avmnist"
    data_fp: "DATA/avmnist/train_subset.csv"
    target_modality: !Modality "multimodal"
    split: "train"
    shuffle: True
    drop_last: True
    pin_memory: True

  validation:
    dataset: "avmnist"
    data_fp: "DATA/avmnist/validation_subset.csv"
    target_modality: !Modality "multimodal"
    split: "valid"
    drop_last: True
    pin_memory: True
    selected_missing_types:
      - "zi"

  test:
    dataset: "avmnist"
    data_fp: "DATA/avmnist/test_subset.csv"
    target_modality: !Modality "multimodal"
    split: "test"
    drop_last: True
    pin_memory: True
    selected_missing_types:
      - "zi"


model:
  name: "AVMNIST"
  pretrained_path: "experiments/avmnist/models/AVMNIST_(Classification):_Baseline_Training/{run_id}/avmnist_model__loss_best.pth"
  audio_encoder: !MNISTAudio
    conv_block_one_args: !ConvBlock
      conv_one_in: 1
      conv_one_out: 32
    conv_block_two_args: !ConvBlock
      conv_one_in: 32
      conv_one_out: 32
    conv_batch_norm: True
    hidden_dim: 64
  image_encoder: !MNISTImage
    conv_block_one_one_args: !ConvBlock
      conv_one_in: 1
      conv_one_out: 32
    conv_block_one_two_args: !ConvBlock
      conv_one_in: 32
      conv_one_out: 64
    conv_block_two_one_args: !ConvBlock
      conv_one_in: 64
      conv_one_out: 64
    conv_block_two_two_args: !ConvBlock
      conv_one_in: 64
      conv_one_out: 64
    hidden_dim: 128
    conv_batch_norm: True
  hidden_dim: 128
  dropout: 0.5
  fusion_fn: "concat"


cmam:
  name: "BasicCMAM"
  input_encoder_info:
    Image: !MNISTImage
      conv_block_one_one_args: !ConvBlock
        conv_one_in: 1
        conv_one_out: 32
      conv_block_one_two_args: !ConvBlock
        conv_one_in: 32
        conv_one_out: 64
      conv_block_two_one_args: !ConvBlock
        conv_one_in: 64
        conv_one_out: 64
      conv_block_two_two_args: !ConvBlock
        conv_one_in: 64
        conv_one_out: 64
      hidden_dim: 128
      conv_batch_norm: True
  target_modality: !Modality "audio"
  assoc_net_input_size: 128
  assoc_net_hidden_size: 256
  assoc_net_output_size: 64
  assoc_dropout: 0.4
  assoc_use_bn: True 
  target_missing_type: "zi"

training:
  epochs: 25
  num_modalities: 2
  batch_size: 256
  optimizer: "adam"
  optim_kwargs:
    weight_decay: 0.0001
    lr: 0.001
    betas: [0.9, 0.999]
  criterion: "cmam"
  criterion_kwargs:
    cosine_weight: 1.0
    mse_weight: 1.0
    mae_weight: 1.0
    cls_weight: 0.05
    rec_weight: 1.0
  target_missing_type: "zi"
  do_tsne: False
  early_stopping: True
  early_stopping_patience: 5
  early_stopping_min_delta: 0.001
  
logging:
  save_metric: "loss"
  log_path: "experiments/avmnist/logs/{experiment_name}/{run_id}/"
  model_output_path: "experiments/avmnist/models/{experiment_name}/{run_id}/cmam_I_To_A_{save_metric}.pth" 
  metrics_path: "experiments/avmnist/metrics/{experiment_name}/{run_id}/cmam_I_to_A"

metrics:
  prediction_metrics:
    Accuracy:
      function: "sklearn.metrics.accuracy_score"
    F1_Micro:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "micro"
    F1_Macro:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "macro"
    F1_Weighted:
      function: "sklearn.metrics.f1_score"
      kwargs:
        average: "weighted"
    Precision_Macro:
      function: "sklearn.metrics.precision_score"
      kwargs:
        average: "macro"
        zero_division: 0
    Recall_Macro:
      function: "sklearn.metrics.recall_score"
      kwargs:
        average: "macro"
        zero_division: 0
    Precision_Weighted:
      function: "sklearn.metrics.precision_score"
      kwargs:
        average: "weighted"
        zero_division: 0
    Recall_Weighted:
      function: "sklearn.metrics.recall_score"
      kwargs:
        average: "weighted"
        zero_division: 0
    Precision_Micro:
      function: "sklearn.metrics.precision_score"
      kwargs:
        average: "micro"
        zero_division: 0
    Recall_Micro:
      function: "sklearn.metrics.recall_score"
      kwargs:
        average: "micro"
        zero_division: 0
    ConfusionMatrix:
      function: "sklearn.metrics.confusion_matrix"
      kwargs:
        labels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]